name:
  Deploy frontend to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main 
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.deploy.yml'

permissions:
  id-token: write
  contents: read

jobs:
  copy-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Copy files to the s3 website content bucket
        working-directory: ./frontend/
        run:
          aws s3 sync html/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/

      - name: Invalidate Cloudfront cache
        working-directory: ./frontend/
        run:
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"